---
repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.17.0
    hooks:
      - id: commitizen
        stages:
          - commit-msg
  - repo: local
    hooks:
      - id: black
        name: black
        entry: make black_check
        language: system
        types:
          - python
        stages:
          - commit
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: make isort_check
        language: system
        types:
          - python
        stages:
          - commit
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: make flake8
        language: system
        types:
          - python
        stages:
          - commit
  - repo: local
    hooks:
      - id: pytest_full
        name: pytest full
        entry: make test
        language: system
        require_serial: true
        types:
          - python
        stages:
          - commit
          - push