---
repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.16.0
    hooks:
      - id: commitizen
        stages:
          - commit-msg
  - repo: local
    hooks:
      - id: tests_staged
        name: pytest staged
        entry: make test_staged
        language: system
        types:
          - python
        stages:
          - commit
  - repo: local
    hooks:
      - id: tests
        name: pytest
        entry: make test
        language: system
        types:
          - python
        stages:
          - push
  - repo: local
    hooks:
      - id: format
        name: black
        entry: make black
        language: system
        types:
          - python
        stages:
          - commit
  - repo: local
    hooks:
      - id: lint
        name: flake8
        entry: make flake8
        language: system
        types:
          - python
        stages:
          - commit